### ISSUE TITLE
Add `ddev-get` as a topic 

### ISSUE THREAD

**Issue by tyler36** [iljapolanskis/ddev-buggregator#3]
Thanks for creating the addon!

Would you mind add `ddev-get` as a topic. This will allow others to discover this addon via `ddev get --list --all`

## Steps
![github-settings](https://github.com/iljapolanskis/ddev-buggregator/assets/7234392/d240c69e-983b-4928-93db-2d7b1875be01)

![ddev-topics](https://github.com/iljapolanskis/ddev-buggregator/assets/7234392/eb7f3650-57b5-46e0-aac9-30d8bc3ae379)

**Comment by iljapolanskis** [comment]
Done  👍

**Comment by tyler36** [comment]
Confirmed.

```shell
$ ddev get --list --all
...
│ iljapolanskis/ddev-buggregator                    │ Buggregator service for DDEV (similar to Ray, but  │
```

Thanks you.
